/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CursosNuevoRouteImport } from './routes/cursos.nuevo'
import { Route as CursosIdReporteRouteImport } from './routes/cursos.$id.reporte'
import { Route as CursosIdParticipantesRouteImport } from './routes/cursos.$id.participantes'
import { Route as CursosIdEditarRouteImport } from './routes/cursos.$id.editar'
import { Route as CursosIdAsistenciaRouteImport } from './routes/cursos.$id.asistencia'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosNuevoRoute = CursosNuevoRouteImport.update({
  id: '/cursos/nuevo',
  path: '/cursos/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosIdReporteRoute = CursosIdReporteRouteImport.update({
  id: '/cursos/$id/reporte',
  path: '/cursos/$id/reporte',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosIdParticipantesRoute = CursosIdParticipantesRouteImport.update({
  id: '/cursos/$id/participantes',
  path: '/cursos/$id/participantes',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosIdEditarRoute = CursosIdEditarRouteImport.update({
  id: '/cursos/$id/editar',
  path: '/cursos/$id/editar',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosIdAsistenciaRoute = CursosIdAsistenciaRouteImport.update({
  id: '/cursos/$id/asistencia',
  path: '/cursos/$id/asistencia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/cursos/nuevo': typeof CursosNuevoRoute
  '/cursos/$id/asistencia': typeof CursosIdAsistenciaRoute
  '/cursos/$id/editar': typeof CursosIdEditarRoute
  '/cursos/$id/participantes': typeof CursosIdParticipantesRoute
  '/cursos/$id/reporte': typeof CursosIdReporteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/cursos/nuevo': typeof CursosNuevoRoute
  '/cursos/$id/asistencia': typeof CursosIdAsistenciaRoute
  '/cursos/$id/editar': typeof CursosIdEditarRoute
  '/cursos/$id/participantes': typeof CursosIdParticipantesRoute
  '/cursos/$id/reporte': typeof CursosIdReporteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/cursos/nuevo': typeof CursosNuevoRoute
  '/cursos/$id/asistencia': typeof CursosIdAsistenciaRoute
  '/cursos/$id/editar': typeof CursosIdEditarRoute
  '/cursos/$id/participantes': typeof CursosIdParticipantesRoute
  '/cursos/$id/reporte': typeof CursosIdReporteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/cursos/nuevo'
    | '/cursos/$id/asistencia'
    | '/cursos/$id/editar'
    | '/cursos/$id/participantes'
    | '/cursos/$id/reporte'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/cursos/nuevo'
    | '/cursos/$id/asistencia'
    | '/cursos/$id/editar'
    | '/cursos/$id/participantes'
    | '/cursos/$id/reporte'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/cursos/nuevo'
    | '/cursos/$id/asistencia'
    | '/cursos/$id/editar'
    | '/cursos/$id/participantes'
    | '/cursos/$id/reporte'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  CursosNuevoRoute: typeof CursosNuevoRoute
  CursosIdAsistenciaRoute: typeof CursosIdAsistenciaRoute
  CursosIdEditarRoute: typeof CursosIdEditarRoute
  CursosIdParticipantesRoute: typeof CursosIdParticipantesRoute
  CursosIdReporteRoute: typeof CursosIdReporteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/nuevo': {
      id: '/cursos/nuevo'
      path: '/cursos/nuevo'
      fullPath: '/cursos/nuevo'
      preLoaderRoute: typeof CursosNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$id/reporte': {
      id: '/cursos/$id/reporte'
      path: '/cursos/$id/reporte'
      fullPath: '/cursos/$id/reporte'
      preLoaderRoute: typeof CursosIdReporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$id/participantes': {
      id: '/cursos/$id/participantes'
      path: '/cursos/$id/participantes'
      fullPath: '/cursos/$id/participantes'
      preLoaderRoute: typeof CursosIdParticipantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$id/editar': {
      id: '/cursos/$id/editar'
      path: '/cursos/$id/editar'
      fullPath: '/cursos/$id/editar'
      preLoaderRoute: typeof CursosIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$id/asistencia': {
      id: '/cursos/$id/asistencia'
      path: '/cursos/$id/asistencia'
      fullPath: '/cursos/$id/asistencia'
      preLoaderRoute: typeof CursosIdAsistenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  CursosNuevoRoute: CursosNuevoRoute,
  CursosIdAsistenciaRoute: CursosIdAsistenciaRoute,
  CursosIdEditarRoute: CursosIdEditarRoute,
  CursosIdParticipantesRoute: CursosIdParticipantesRoute,
  CursosIdReporteRoute: CursosIdReporteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
